required = [
  "github.com/onsi/ginkgo",
  "github.com/onsi/ginkgo/ginkgo",
  "github.com/onsi/gomega",
]

[[constraint]]
  name = "github.com/onsi/ginkgo"
  revision = "03ffd3f46debf00c49ed76d5dbb564ef4839adfe"

[[constraint]]
  name = "github.com/onsi/gomega"
  revision = "649b44d988ce182cabcda7dba01fcf3b6179ad19"

[prune]
  go-tests = true
  unused-packages = true
